# ./.tmuxinator.yml

name: puddle

windows:
  - root:
      layout: 6456,228x23,0,0{175x23,0,0,9,52x23,176,0,10}
      panes:
        - <%= ENV["EDITOR"] || "vim" || "vi" %> .
        - npm run <%= @settings["serve-cmd"] || "serve" %>
